### ISSUE TITLE
Running multiple optimizations in parallel

### ISSUE THREAD

**Issue by FelixStege** [meco-group/fatrop#21]
I'm attempting to run multiple MPCs using CasADi and fatrop. However, I've encountered an issue where running multiple optimizations in parallel (using Python threads) yields inconsistent results with each execution. When running a single MPC, the results are always consistent.
This behavior doesn't occur when running IPOPT in parallel.

Is this a known limitation with fatrop, or are there any options available to enable proper parallel computation? Any help would be appreciated!

Thank you in advance!

**Comment by lvanroye** [comment]
Hi Felix, 

Is it correct that a single fatrop solver instance is created in the main thread, and the solve function is called from multiple threads in parallel?

If that's the case each thread accesses the same solver instance concurrently, which may lead to conflicts as the solver is not designed to be thread-safe. I guess in contrast to fatrop calling the Ipopt solver is thread-safe, at the cost of requiring dynamic memory allocation when solving the problem (fatrop only does dynamic memory allocation upon solver instantiation). For true parallel execution, each thread should have its own independent fatrop solver instance.

**Comment by lvanroye** [comment]
Anyway thanks for reporting the problem, I will build in a safety mechanism which tries to detect concurrent usage of a single fatrop instance.

**Comment by FelixStege** [comment]
Hi Lander,
thanks for the quick reply. Actually we are starting an instance for each optimization. So this should not be the problem.

**Comment by lvanroye** [comment]
Hello, would it be possible to attach a (potentially simplified) python script which I can use to reproduce this behavior?

**Comment by FelixStege** [comment]
Hi, unfortunately, I wasn't able to reproduce the issue with a simpler optimization problem. I'm currently using the [agentlib framework](https://github.com/RWTH-EBC/AgentLib-MPC) for optimization, which streamlines the notation in CasADi. Converting the model to plain CasADi code would require significant effort, and I won't have the time to do that in the next few days. However, I might be able to work on it in the coming weeks.

Thanks again for the quick support!

**Comment by lvanroye** [comment]
Hi Felix, 

If you don't like to share your full code you can also look at casadi's serialization functionality. You can for example serialize your full opti problem, such that you don´t have to share the code that produces this opti instance. I'd really want to figure out if there is something that goes wrong on the fatrop side as it is behiavor that is not supposed to happen.


Lander

**Comment by FelixStege** [comment]
Hi Lander,

I had some time to investigate the issue further, and it turns out the problem isn't related to fatrop but stems from my own code. There was a small bug causing multiple MPCs to send the same variable simultaneously. Depending on CPU speed, the execution order of the MPCs varied, which affected the final results (leading to the random factor).

This clears up the issue, so it can be closed.

Apologies for any confusion caused!

**Comment by lvanroye** [comment]
Hi Felix, 
Thanks for figuring it out and keeping us informed!
Good luck with the rest of your project.
